// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqygjbzdfwigxyfrlkfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeWdqYnpkZndpZ3h5ZnJsa2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODUzMzYsImV4cCI6MjA3MDc2MTMzNn0.Bvd25j-sJCb_muXm5Vxs3cz3WaIw_B8ZlLERq6gmCqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});